import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {join} from 'node:path';
const sha=async file=>createHash('sha256').update(await readFile(file)).digest('hex');
const cmd=(...args)=>{try{return execFileSync(args[0],args.slice(1),{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim()}catch{return null}};
const read=async path=>{try{return await readFile(path,'utf8')}catch{return ''}};
const parsed=async path=>{try{return JSON.parse(await readFile(path,'utf8'))}catch{return null}};
const log=await read('docs/receipts/test-output.log'),build=await read('docs/receipts/build-output.log');
const pass=Number(log.match(/(?:ℹ|#) pass (\d+)/)?.[1]??0),fail=Number(log.match(/(?:ℹ|#) fail (\d+)/)?.[1]??0);
const web=await parsed('docs/receipts/web-e2e-results.json'),infra=await parsed('docs/receipts/infrastructure-receipt.json');
const ids=[...new Set([...log.matchAll(/(?:G0|LOCAL|NVIDIA)-[A-Z0-9-]+/g)].map(m=>m[0]))].sort();
async function files(dir){let result=[];for(const entry of await readdir(dir,{withFileTypes:true})){if(['node_modules','data','dist','test-results','playwright-report','.git','.build','.swiftpm'].includes(entry.name))continue;const path=join(dir,entry.name);if(entry.isDirectory())result.push(...await files(path));else if(!path.startsWith('docs/receipts/')&&entry.name!=='.env'&&entry.name!=='app.js'&&entry.name!=='.DS_Store')result.push(path);}return result;}
const manifest=[];for(const path of (await files('.')).sort())manifest.push({path,sha256:await sha(path)});
const sourceHash=createHash('sha256').update(JSON.stringify(manifest)).digest('hex');await writeFile('docs/receipts/source-manifest.json',JSON.stringify({sha256:sourceHash,files:manifest},null,2)+'\n');
const receipt={source_commit:cmd('git','rev-parse','HEAD'),source_snapshot_sha256:sourceHash,source_manifest:'docs/receipts/source-manifest.json',environment:'linux_local_development_and_synthetic_infrastructure',created_at:new Date().toISOString(),node:process.version,npm:cmd('npm','--version'),dependency_lock_sha256:await sha('package-lock.json'),migration:{file:'001_foundation.sql',sha256:await sha('db/migrations/001_foundation.sql'),applied_in_fixture:!!infra?.checks?.find(c=>c.id==='INFRA-PG-01'&&c.status==='passed')},images_lock_sha256:await sha('infra/images.lock.json'),feature_manifest_version:2,client_builds:{web:build.includes('tsc')?'typescript_compiled':'unverified',ios:'Swift6_syntax_and_portable_model_tests_passed_iOS_SDK_build_unrun'},tests:{mode:'synthetic_and_local',total:pass+fail,passed:pass,failed:fail,ids,log:'docs/receipts/test-output.log'},web_e2e:{passed:web?.stats?.expected??0,failed:web?.stats?.unexpected??null,skipped:web?.stats?.skipped??null,projects:['desktop','mobile'],log:'docs/receipts/web-e2e-output.log',result:'docs/receipts/web-e2e-results.json'},infrastructure:{checks:infra?.checks??[],mode:'synthetic_only',receipt:'docs/receipts/infrastructure-receipt.json'},pdf:{opening_and_text_extraction:'passed_pdfinfo_pdftotext',tagged:true,conformance:'PDF-UA_and_human_screen_reader_unverified',sample:'docs/receipts/sample-draft.pdf'},integrations:{nvidia:'adapter_fixture_tested_no_live_credentials_or_processor_signoff',calendar:'synthetic_fixture_only_live_writes_disabled',vm:'provider_disabled'},production_gates_passed:[],gate_status_ref:'docs/receipts/gate-status.json',g5:'staged_not_claimed',clean_checkout:{local_install_build_and_smoke:'passed',receipt:'docs/receipts/clean-checkout.json',full_production_contract:'unpassed_requires_Xcode_and_other_gate_evidence'},operator_signoff:null};
await writeFile('docs/receipts/local-test-receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(`Recorded ${pass} local/fixture tests, ${receipt.web_e2e.passed} browser checks. No production gate promoted.`);
